[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
vouch_verifier = "AgG8EAwpeWqjoJQBtUY5SHX38gYpsVhcG4x7UuRHwxk7"

[programs.devnet]
vouch_verifier = "AgG8EAwpeWqjoJQBtUY5SHX38gYpsVhcG4x7UuRHwxk7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/vouch-verifier"]
types = "apps/web/src/idl/"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.anchor.json -t 1000000 tests/**/*.ts"
